name: qoremed_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  local_auth: ^0.6.3+4
  flutter_launcher_icons: ^0.8.1
  overlay_support: ^1.0.5
  firebase_messaging: ^7.0.3
  flutter_time_picker_spinner: ^1.0.6+1
  printing: ^3.6.1
  dots_indicator: ^0.0.4
  flutter_html: ^0.8.2
  device_apps: ^1.2.0
  http_auth: ^0.3.0
  webview_flutter: ^1.0.1
  flutter_webview_plugin: ^0.3.11
  search_map_place: ^0.3.0
  flutter_google_maps: ^4.0.0
  map_controller: ^0.8.0
  flutter_map: ^0.9.0
  geocoder: ^0.2.1
  url_launcher: ^5.1.3
  path_provider:
  sqflite:

  flutter_slidable: ^0.5.4
  flutter:
    sdk: flutter
  easy_localization: ^2.3.2
  image_picker: ^0.6.7+2
  equatable: ^1.2.0
  flutter_bloc: ^4.0.0
  flutter_staggered_grid_view: ^0.3.0
  shared_preferences: ^0.5.6
  percent_indicator: ^2.1.1+1
  flutter_rating_bar: ^3.0.0
  http:
  qr_flutter: ^3.1.0
  qrscan: ^0.2.17
  table_calendar: ^2.2.3
  instant: ^0.1.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/launchericon.png"
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/languages/
    - assets/images/logo_dark.png

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
